[workspace]
members = ["ferrex-server", "ferrex-core", "ferrex-player"]
exclude = [
    "lucide_icons_iced_0.14",
    "iced_fork",
    "iced_video_player",
    "iced_video_player_wayland",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ferrex Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Lowband21/rusty-media-server"
documentation = "https://docs.rs/ferrex"
homepage = "https://github.com/Lowband21/ferrex_media_server"
readme = "README.md"
keywords = ["media-server", "streaming", "rust", "video", "transcoding"]
categories = ["multimedia", "web-programming::http-server"]

[workspace.dependencies]
# Async runtime
tokio = { version = "1.40", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# HTTP/Web
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "cors", "trace"] }
reqwest = { version = "0.11", features = ["json"] }

# Async traits
async-trait = "0.1"

# Database
surrealdb = { version = "1.5", features = ["kv-mem"] }
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "uuid",
    "migrate",
    "bigdecimal",
    "ipnetwork",
] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Media processing
ffmpeg-next = "7.0"

# File system
walkdir = "2.5"

# Image processing
image = "0.25"

# Cryptography
sha2 = "0.10"

# Regex
regex = "1.10"

# UUID generation
uuid = { version = "1.10", features = ["v4", "v5", "v7", "serde", "std"] }

# Configuration
config = "0.14"

# URL
url = "2.5.4"

# tmdb
tmdb-api = "0.9.1"

# Testing
mockall = "0.13"
tempfile = "3.12"

# Concurrency
rayon = "1.10.0"

# Fuzzy matching
fuzzy-matcher = "0.3"

# Authentication
jsonwebtoken = "9.3"
argon2 = "0.5.3"

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3

[profile.dev.package.ferrex-player]
opt-level = 2

[profile.release.package.ferrex-player]
opt-level = 3

# Documentation settings
[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# Define documentation lints
[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"
private_intra_doc_links = "warn"
missing_crate_level_docs = "warn"
private_doc_tests = "warn"
invalid_codeblock_attributes = "warn"
invalid_rust_codeblocks = "warn"
bare_urls = "warn"

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
